version: "3.7"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
  kibana:
    image: docker.elastic.co/kibana/kibana:7.0.0
    container_name: kibana
    ports:
      - 5601:5601
  redis:
    image: "redis:alpine"
    container_name: cache
    expose:
      - 6379
  app:
    build: .
    volumes:
      - ./:/usr/src/app
    ports:
      - 8080:8080
    command: npm run dev
