version: "3.7"

services:
  redis:
    image: "redis:alpine"
    container_name: ts-cache
    expose:
      - 6379
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.2
    ports:
      - "5601:5601"
  mongo:
    image: "mongo:latest"
    container_name: "ts-mongodb"
    expose:
      - 27017
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/mongodb:/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet
  app:
    build: .
    container_name: "ts-server"
    volumes:
      - ./:/usr/src/app
    ports:
      - 8080:8080
    command: npm run dev
