version: "3.7"

services:
  redis:
    image: "redis:alpine"
    container_name: cache
    expose:
      - 6379
  app:
    build: .
    volumes:
      - ./:/usr/src/app
    ports:
      - 8080:8080
    command: npm run dev
